### ISSUE TITLE
[bin] Windows support

### ISSUE THREAD

**Issue by conor-cafferkey-sociomantic** [sociomantic-tsunami/lochness#16]
### Currently

In `package.json` we have:
```
...
 "bin": {
    "loch": "bin/loch.js",
    "visualTest": "bin/visualTests.js",
    "loch:build": "bin/build.js"
  },
...
```

These are available to the host package that has imported LochNess as a dependency. On Windows this creates `.bat` files with the same filename, e.g: `loch` 👉 `loch.bat`. 

### Problem

`:` is not a valid character on Windows filesystems, so `loch:build` doesn’t work.

### Wanted

- [ ] Add a `loch-build` script that does the same as current `loch:build`
- [ ] Deprecate `loch:build`

**Comment by conor-cafferkey-sociomantic** [comment]
This will be handled as part of https://github.com/sociomantic-tsunami/lochness/issues/24

**Comment by mahmoud-zakria-sociomantic** [comment]
Done and will be deployed with the next release.
