### ISSUE TITLE
Remove Nessie-specific hardcodedness

### ISSUE THREAD

**Issue by conor-cafferkey-sociomantic** [sociomantic-tsunami/lochness#24]
### Currently

LochNess is built in such a way that it can only work with Nessie.

### Problem

This kinda defeats the purpose of it being a separate project...

### Wanted

- [ ] We should not be expecting `/dist/displayComponents.js` and `dist/displayComponents.css` to exist relative to the components package that we are displaying
- [ ] Restore the specific command line arguments for the display components `src`, `dist` and `defaults` paths

**Comment by conor-cafferkey-sociomantic** [comment]
For reference, there are 4 things that LochNess needs to retrieve from a given component library (e.g. Nessie) in order to display it:
- the dist JS file: containing the actual components to display
-  `package.json`: to fetch the name of the component library and its version number
- the `src/` folder: to generate the prop documentation
-  JSON file containing “default” component props to show

(With this in mind we’ll need to have 4 command-line arguments to specify each of the above)

**Comment by mahmoud-zakria-sociomantic** [comment]
@conor-cafferkey-sociomantic  in this case we have to bring back this path `./` which is in `cli-args` module's default value is `node_modules/nessie-ui/` or do I need to specify `package.json` itself in the path? like `--componentsLib=./package.json`

**Comment by conor-cafferkey-sociomantic** [comment]
> in this case we have to bring back this path `./` which is in `cli-args`

True.

I think it could be something like this:

- `--lib` (required): the path to the npm package containing the component library (`./` in your example above)
- `--dist` (optional): the path of the JS entry point for the components, relative to the  npm package (e.g. `dist/myComponents.js`). If this arg is not specified we use the entrypoint specified by the package (i.e. `main` in `package.json`<sup>*</sup>)
- `--src` (optional): the path of the JS source files of the components, relative to the npm package. If this arg is not specified then we use `src/`
- `--props` (optional): the path to the “default”/“demo” props to show. If not specified then we don’t load demo props.

The main point is still this:
> We should not be expecting `/dist/displayComponents.js` and `dist/displayComponents.css` to exist relative to the components package that we are displaying

Likewise, we should not assume that `src/defaults.json` exists.

On the other hand, we _can_ assume that:
- `package.json` exists relative to the `--lib` path
- the dist file (JS bundle) is whatever is specified in `package.json` **unless** a specific `--dist` arg is supplied
- the source files will be found in `src/` **unless** a specific `--src` arg is supplied




-----
<sup>*</sup> and if `main` is not specified in `package.json` then we fall back to `index.js`

**Comment by conor-cafferkey-sociomantic** [comment]
Actually, even the `--lib` argument could be optional, as it could default to `./`
