### ISSUE TITLE
Start Lochness with specific set of components from the selected library

### ISSUE THREAD

**Issue by ericgraficode** [sociomantic-tsunami/lochness#5]
**Currently**
Lochness renders the whole library of components it´s passed to it.

**Problem**
For example in the case of Nessie you will need to build all the library even if you need just to work in one component, same goes for testing.

**Wanted**
The ability to cherry-pick one or some specific components from a library and start Lochness with them.
So you will be able to start Lochness with a script similar to:

`yarn start InputField`

**Comment by conor-cafferkey-sociomantic** [comment]
Once https://github.com/sociomantic-tsunami/lochness/issues/24 is done you’ll  be able to do this by specifying a custom entry point
